mysql:
  image: mysql
  container_name: betteram_database
  environment:
    MYSQL_DATABASE: betteram
    MYSQL_ROOT_PASSWORD: 123456

redis:
  image: redis:alpine
  container_name: betteram_redis

#node:
#  build: .
#  dockerfile: ./docker/node/Dockerfile
#  container_name: node
#  volumes_from:
#    - php

php:
  build: .
  dockerfile: ./docker/php/Dockerfile
  container_name: betteram_php
  working_dir: /var/www/betteram
  volumes:
    - .:/var/www/betteram

nginx:
  image: nginx:alpine
  container_name: betteram_nginx
  working_dir: /var/www/betteram
  links:
    - php
  volumes_from:
    - php
  volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 8080:80
