mysql:
  image: mysql
  container_name: betteram_database
  environment:
    MYSQL_DATABASE: betteram
    MYSQL_ROOT_PASSWORD: 123456

redis:
  image: redis:alpine
  container_name: betteram_redis

php:
  build: .
  dockerfile: ./docker/php/Dockerfile
  container_name: betteram_php
  volumes:
    - .:/var/www/betteram

nginx:
  image: nginx:alpine
  container_name: betteram_nginx
  volumes_from:
    - php
  volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
    - 8000:80
